Data <- read_csv('/PathTo/DataFile/AllOrgs_GenePer.csv', col_names = TRUE, col_types = NULL, na = "NA", skip = 0, n_max = -1, progress = interactive())
View(Data)

CarnivTot <- mean(c(Data[38,2],Data[38,3],Data[38,4],Data[38,5]))
Actin <- mean(c(Data[1,2],Data[1,3],Data[1,4],Data[1,5]))
AGal <- mean(c(Data[2,2],Data[2,3],Data[2,4],Data[2,5]))
AltOx <- mean(c(Data[3,2],Data[3,3],Data[3,4],Data[3,5]))
NHTrans <- mean(c(Data[4,2],Data[4,3],Data[4,4],Data[4,5]))
AspPep <- mean(c(Data[5,2],Data[5,3],Data[5,4],Data[5,5]))
ATP_ADP <- mean(c(Data[6,2],Data[6,3],Data[6,4],Data[6,5]))
ATP <- mean(c(Data[7,2],Data[7,3],Data[7,4],Data[7,5]))
BGal <- mean(c(Data[8,2],Data[8,3],Data[8,4],Data[8,5]))
BGluc <- mean(c(Data[9,2],Data[9,3],Data[9,4],Data[9,5]))
Chit <- mean(c(Data[10,2],Data[10,3],Data[10,4],Data[10,5]))
CinAlc <- mean(c(Data[11,2],Data[11,3],Data[11,4],Data[11,5]))
CycNPhos <- mean(c(Data[12,2],Data[12,3],Data[12,4],Data[12,5]))
CystPep <- mean(c(Data[13,2],Data[13,3],Data[13,4],Data[13,5]))
EndoNuc <- mean(c(Data[14,2],Data[14,3],Data[14,4],Data[14,5]))
FormateDH <- mean(c(Data[15,2],Data[15,3],Data[15,4],Data[15,5]))
FrucBPA <- mean(c(Data[16,2],Data[16,3],Data[16,4],Data[16,5]))
Glucosid <- mean(c(Data[17,2],Data[17,3],Data[17,4],Data[17,5]))
GlutTrans <- mean(c(Data[18,2],Data[18,3] ,Data[18,4],Data[18,5]))
Lipase <- mean(c(Data[19,2],Data[19,3],Data[19,4],Data[19,5]))
LipTrans <- mean(c(Data[20,2],Data[20,3],Data[20,4],Data[20,5]))
MethylNH <- mean(c(Data[21,2],Data[21,3],Data[21,4],Data[21,5]))
Perox <- mean(c(Data[22,2],Data[22,3],Data[22,4],Data[22,5]))
Phosp <- mean(c(Data[23,2],Data[23,3],Data[23,4],Data[23,5]))
Phoslip <- mean(c(Data[24,2],Data[24,3],Data[24,4],Data[24,5]))
Polygal <- mean(c(Data[25,2],Data[25,3],Data[25,4],Data[25,5]))
PolygalInhib <- mean(c(Data[26,2],Data[26,3],Data[26,4],Data[26,5]))
ProtHomo <- mean(c(Data[27,2],Data[27,3],Data[27,4],Data[27,5]))
RiboNuc <- mean(c(Data[28,2],Data[28,3],Data[28,4],Data[28,5]))
SerCarPep <- mean(c(Data[29,2],Data[29,3],Data[29,4],Data[29,5]))
NaTrans <- mean(c(Data[30,2],Data[30,3],Data[30,4],Data[30,5]))
SuperOx <- mean(c(Data[31,2],Data[31,3],Data[31,4],Data[31,5]))
Symplast <- mean(c(Data[32,2],Data[32,3],Data[32,4],Data[32,5]))
ThioGluc <- mean(c(Data[33,2],Data[33,3],Data[33,4],Data[33,5]))
H20Chan <- mean(c(Data[34,2],Data[34,3],Data[34,4],Data[34,5]))
Xyl <- mean(c(Data[35,2],Data[35,3],Data[35,4],Data[35,5]))
HeatShock <- mean(c(Data[36,2],Data[36,3],Data[36,4],Data[36,5]))

CarnivTot.SD <- sd(c(Data[38,2],Data[38,3],Data[38,4],Data[38,5]))
Actin.SD <- sd(c(Data[1,2],Data[1,3],Data[1,4],Data[1,5]))
AGal.SD <- sd(c(Data[2,2],Data[2,3],Data[2,4],Data[2,5]))
AltOx.SD <- sd(c(Data[3,2],Data[3,3],Data[3,4],Data[3,5]))
NHTrans.SD <- sd(c(Data[4,2],Data[4,3],Data[4,4],Data[4,5]))
AspPep.SD <- sd(c(Data[5,2],Data[5,3],Data[5,4],Data[5,5]))
ATP_ADP.SD <- sd(c(Data[6,2],Data[6,3],Data[6,4],Data[6,5]))
ATP.SD <- sd(c(Data[7,2],Data[7,3],Data[7,4],Data[7,5]))
BGal.SD <- sd(c(Data[8,2],Data[8,3],Data[8,4],Data[8,5]))
BGluc.SD <- sd(c(Data[9,2],Data[9,3],Data[9,4],Data[9,5]))
Chit.SD <- sd(c(Data[10,2],Data[10,3],Data[10,4],Data[10,5]))
CinAlc.SD <- sd(c(Data[11,2],Data[11,3],Data[11,4],Data[11,5]))
CycNPhos.SD <- sd(c(Data[12,2],Data[12,3],Data[12,4],Data[12,5]))
CystPep.SD <- sd(c(Data[13,2],Data[13,3],Data[13,4],Data[13,5]))
EndoNuc.SD <- sd(c(Data[14,2],Data[14,3],Data[14,4],Data[14,5]))
FormateDH.SD <- sd(c(Data[15,2],Data[15,3],Data[15,4],Data[15,5]))
FrucBPA.SD <- sd(c(Data[16,2],Data[16,3],Data[16,4],Data[16,5]))
Glucosid.SD <- sd(c(Data[17,2],Data[17,3],Data[17,4],Data[17,5]))
GlutTrans.SD <- sd(c(Data[18,2],Data[18,3],Data[18,4],Data[18,5]))
Lipase.SD <- sd(c(Data[19,2],Data[19,3],Data[19,4],Data[19,5]))
LipTrans.SD <- sd(c(Data[20,2],Data[20,3],Data[20,4],Data[20,5]))
MethylNH.SD <- sd(c(Data[21,2],Data[21,3],Data[21,4],Data[21,5]))
Perox.SD <- sd(c(Data[22,2],Data[22,3],Data[22,4],Data[22,5]))
Phosp.SD <- sd(c(Data[23,2],Data[23,3],Data[23,4],Data[23,5]))
Phoslip.SD <- sd(c(Data[24,2],Data[24,3],Data[24,4],Data[24,5]))
Polygal.SD <- sd(c(Data[25,2],Data[25,3],Data[25,4],Data[25,5]))
PolygalInhib.SD <- sd(c(Data[26,2],Data[26,3],Data[26,4],Data[26,5]))
ProtHomo.SD <- sd(c(Data[27,2],Data[27,3],Data[27,4],Data[27,5]))
RiboNuc.SD <- sd(c(Data[28,2],Data[28,3],Data[28,4],Data[28,5]))
SerCarPep.SD <- sd(c(Data[29,2],Data[29,3],Data[29,4],Data[29,5]))
NaTrans.SD <- sd(c(Data[30,2],Data[30,3],Data[30,4],Data[30,5]))
SuperOx.SD <- sd(c(Data[31,2],Data[31,3],Data[31,4],Data[31,5]))
Symplast.SD <- sd(c(Data[32,2],Data[32,3],Data[32,4],Data[32,5]))
ThioGluc.SD <- sd(c(Data[33,2],Data[33,3],Data[33,4],Data[33,5]))
H20Chan.SD <- sd(c(Data[34,2],Data[34,3],Data[34,4],Data[34,5]))
Xyl.SD <- sd(c(Data[35,2],Data[35,3],Data[35,4],Data[35,5]))
HeatShock.SD <- sd(c(Data[36,2],Data[36,3],Data[36,4],Data[36,5]))

par(mfrow=c(5,6))

#CarnivTot
X = seq(-4,4,length=1000)*CarnivTot.SD + CarnivTot
Y = dnorm(X, CarnivTot, CarnivTot.SD)
plot(X, Y, xlab="Percent Representation", ylab ="Probability",main="Total Carnivory-Associated")
abline(v=CarnivTot,lty=2)
abline(v=CarnivTot+CarnivTot.SD,lty=2)
abline(v=CarnivTot+CarnivTot.SD*2,lty=2)
abline(v=CarnivTot+CarnivTot.SD*3,lty=2)
abline(v=CarnivTot-CarnivTot.SD,lty=2)
abline(v=CarnivTot-CarnivTot.SD*2,lty=2)
abline(v=CarnivTot-CarnivTot.SD*3,lty=2)
abline(v=Data[38,6],col="green",lwd=4)
abline(v=Data[38,7],col="blue",lwd=3)
abline(v=Data[38,8],col="red",lwd=3)

#Actin
X = seq(-4,4,length=1000)*Actin.SD + Actin
Y = dnorm(X, Actin, Actin.SD)
plot(X, Y, xlab="Proportion Represented", ylab ="Probability",main="Actin")
abline(v=Actin,lty=2)
abline(v=Actin+Actin.SD,lty=2)
abline(v=Actin+Actin.SD*2,lty=2)
abline(v=Actin+Actin.SD*3,lty=2)
abline(v=Actin-Actin.SD,lty=2)
abline(v=Actin-Actin.SD*2,lty=2)
abline(v=Actin-Actin.SD*3,lty=2)
abline(v=Data[1,6],col="green",lwd=4)
abline(v=Data[1,7],col="blue",lwd=3)
abline(v=Data[1,8],col="red",lwd=3)

#AGal
X = seq(-4,20,length=5000)*AGal.SD + AGal
Y = dnorm(X, AGal, AGal.SD)
plot(X, Y, xlab="Proportion Represented", ylab ="Probability",main="AGal")
abline(v=AGal,lty=2)
abline(v=AGal+AGal.SD,lty=2)
abline(v=AGal+AGal.SD*2,lty=2)
abline(v=AGal+AGal.SD*3,lty=2)
abline(v=AGal+AGal.SD*4,lty=2)
abline(v=AGal+AGal.SD*5,lty=2)
abline(v=AGal+AGal.SD*6,lty=2)
abline(v=AGal+AGal.SD*7,lty=2)
abline(v=AGal+AGal.SD*8,lty=2)
abline(v=AGal+AGal.SD*3,lty=2)
abline(v=AGal+AGal.SD*9,lty=2)
abline(v=AGal+AGal.SD*10,lty=2)
abline(v=AGal+AGal.SD*11,lty=2)
abline(v=AGal+AGal.SD*12,lty=2)
abline(v=AGal+AGal.SD*13,lty=2)
abline(v=AGal+AGal.SD*14,lty=2)
abline(v=AGal-AGal.SD,lty=2)
abline(v=AGal-AGal.SD*2,lty=2)
abline(v=AGal-AGal.SD*3,lty=2)
abline(v=Data[2,6],col="green",lwd=4)
abline(v=Data[2,7],col="blue",lwd=3)
abline(v=Data[2,8],col="red",lwd=3)

#AltOx
X = seq(-4,8,length=1000)*AltOx.SD + AltOx
Y = dnorm(X, AltOx, AltOx.SD)
plot(X, Y, xlab="Percent Representation", ylab ="Probability",main="Alternative Oxidase Activity")
abline(v=AltOx,lty=2)
abline(v=AltOx+AltOx.SD,lty=2)
abline(v=AltOx+AltOx.SD*2,lty=2)
abline(v=AltOx+AltOx.SD*3,lty=2)
abline(v=AltOx-AltOx.SD,lty=2)
abline(v=AltOx-AltOx.SD*2,lty=2)
abline(v=AltOx-AltOx.SD*3,lty=2)
abline(v=Data[3,6],col="green",lwd=4)
abline(v=Data[3,7],col="blue",lwd=3)
abline(v=Data[3,8],col="red",lwd=3)

#NHTrans
X = seq(-4,4,length=1000)*NHTrans.SD + NHTrans
Y = dnorm(X, NHTrans, NHTrans.SD)
plot(X, Y, xlab="Proportion Represented", ylab ="Probability",main="NHTrans")
abline(v=NHTrans,lty=2)
abline(v=NHTrans+NHTrans.SD,lty=2)
abline(v=NHTrans+NHTrans.SD*2,lty=2)
abline(v=NHTrans+NHTrans.SD*3,lty=2)
abline(v=NHTrans-NHTrans.SD,lty=2)
abline(v=NHTrans-NHTrans.SD*2,lty=2)
abline(v=NHTrans-NHTrans.SD*3,lty=2)
abline(v=Data[4,6],col="green",lwd=4)
abline(v=Data[4,7],col="blue",lwd=3)
abline(v=Data[4,8],col="red",lwd=3)

#AspPep
X = seq(-4,4,length=1000)*AspPep.SD + AspPep
Y = dnorm(X, AspPep, AspPep.SD)
plot(X, Y, xlab="Proportion Represented", ylab ="Probability",main="AspPep")
abline(v=AspPep,lty=2)
abline(v=AspPep+AspPep.SD,lty=2)
abline(v=AspPep+AspPep.SD*2,lty=2)
abline(v=AspPep+AspPep.SD*3,lty=2)
abline(v=AspPep+AspPep.SD*4,lty=2)
abline(v=AspPep+AspPep.SD*5,lty=2)
abline(v=AspPep+AspPep.SD*6,lty=2)
abline(v=AspPep+AspPep.SD*7,lty=2)
abline(v=AspPep+AspPep.SD*8,lty=2)
abline(v=AspPep+AspPep.SD*9,lty=2)
abline(v=AspPep+AspPep.SD*10,lty=2)
abline(v=AspPep+AspPep.SD*11,lty=2)
abline(v=AspPep+AspPep.SD*12,lty=2)
abline(v=AspPep+AspPep.SD*13,lty=2)
abline(v=AspPep+AspPep.SD*14,lty=2)
abline(v=AspPep+AspPep.SD*15,lty=2)
abline(v=AspPep+AspPep.SD*16,lty=2)
abline(v=AspPep+AspPep.SD*17,lty=2)
abline(v=AspPep+AspPep.SD*18,lty=2)
abline(v=AspPep+AspPep.SD*19,lty=2)
abline(v=AspPep-AspPep.SD,lty=2)
abline(v=AspPep-AspPep.SD*2,lty=2)
abline(v=AspPep-AspPep.SD*3,lty=2)
abline(v=Data[5,6],col="green",lwd=4)
abline(v=Data[5,7],col="blue",lwd=3)
abline(v=Data[5,8],col="red",lwd=3)

#ATP_ADP
X = seq(-4,4,length=1000)*ATP_ADP.SD + ATP_ADP
Y = dnorm(X, ATP_ADP, ATP_ADP.SD)
plot(X, Y, xlab="Proportion Represented", ylab ="Probability",main="ATP_ADP")
abline(v=ATP_ADP,lty=2)
abline(v=ATP_ADP+ATP_ADP.SD,lty=2)
abline(v=ATP_ADP+ATP_ADP.SD*2,lty=2)
abline(v=ATP_ADP+ATP_ADP.SD*3,lty=2)
abline(v=ATP_ADP-ATP_ADP.SD,lty=2)
abline(v=ATP_ADP-ATP_ADP.SD*2,lty=2)
abline(v=ATP_ADP-ATP_ADP.SD*3,lty=2)
abline(v=Data[6,6],col="green",lwd=4)
abline(v=Data[6,7],col="blue",lwd=3)
abline(v=Data[6,8],col="red",lwd=3)

#ATP
X = seq(-4,8,length=3000)*ATP.SD + ATP
Y = dnorm(X, ATP, ATP.SD)
plot(X, Y, xlab="Proportion Represented", ylab ="Probability",main="ATP")
abline(v=ATP,lty=2)
abline(v=ATP+ATP.SD,lty=2)
abline(v=ATP+ATP.SD,lty=2)
abline(v=ATP+ATP.SD*2,lty=2)
abline(v=ATP+ATP.SD*3,lty=2)
abline(v=ATP+ATP.SD*4,lty=2)
abline(v=ATP+ATP.SD*5,lty=2)
abline(v=ATP+ATP.SD*6,lty=2)
abline(v=ATP+ATP.SD*7,lty=2)
abline(v=ATP+ATP.SD*8,lty=2)
abline(v=ATP-ATP.SD,lty=2)
abline(v=ATP-ATP.SD*2,lty=2)
abline(v=ATP-ATP.SD*3,lty=2)
abline(v=Data[7,6],col="green",lwd=4)
abline(v=Data[7,7],col="blue",lwd=3)
abline(v=Data[7,8],col="red",lwd=3)

#BGal
X = seq(-4,4,length=1000)*BGal.SD + BGal
Y = dnorm(X, BGal, BGal.SD)
plot(X, Y, xlab="Percent Representation", ylab ="Probability",main="Beta-Galactosidase Activity")
abline(v=BGal,lty=2)
abline(v=BGal+BGal.SD,lty=2)
abline(v=BGal+BGal.SD*2,lty=2)
abline(v=BGal+BGal.SD*3,lty=2)
abline(v=BGal-BGal.SD,lty=2)
abline(v=BGal-BGal.SD*2,lty=2)
abline(v=BGal-BGal.SD*3,lty=2)
abline(v=Data[8,6],col="green",lwd=4)
abline(v=Data[8,7],col="blue",lwd=3)
abline(v=Data[8,8],col="red",lwd=3)

#BGluc ###NO HITS
#X = seq(-4,4,length=1000)*BGluc.SD + BGluc
#Y = dnorm(X, BGluc, BGluc.SD)
#plot(X, Y, xlab="Proportion Represented", ylab ="Probability",main="BGluc")
#abline(v=BGluc,lty=2)
#abline(v=BGluc+BGluc.SD,lty=2)
#abline(v=BGluc+BGluc.SD*2,lty=2)
#abline(v=BGluc+BGluc.SD*3,lty=2)
#abline(v=BGluc-BGluc.SD,lty=2)
#abline(v=BGluc-BGluc.SD*2,lty=2)
#abline(v=BGluc-BGluc.SD*3,lty=2)
#abline(v=Data[9,6],col="green",lwd=4)
#abline(v=Data[9,7],col="blue",lwd=3)
#abline(v=Data[9,8],col="red",lwd=3)

#Chit
X = seq(-4,4,length=1000)*Chit.SD + Chit
Y = dnorm(X, Chit, Chit.SD)
plot(X, Y, xlab="Proportion Represented", ylab ="Probability",main="Chit")
abline(v=Chit,lty=2)
abline(v=Chit+Chit.SD,lty=2)
abline(v=Chit+Chit.SD*2,lty=2)
abline(v=Chit+Chit.SD*3,lty=2)
abline(v=Chit-Chit.SD,lty=2)
abline(v=Chit-Chit.SD*2,lty=2)
abline(v=Chit-Chit.SD*3,lty=2)
abline(v=Data[10,6],col="green",lwd=4)
abline(v=Data[10,7],col="blue",lwd=3)
abline(v=Data[10,8],col="red",lwd=3)

#CinAlc
X = seq(-4,4,length=1000)*CinAlc.SD + CinAlc
Y = dnorm(X, CinAlc, CinAlc.SD)
plot(X, Y, xlab="Proportion Represented", ylab ="Probability",main="CinAlc")
abline(v=CinAlc,lty=2)
abline(v=CinAlc+CinAlc.SD,lty=2)
abline(v=CinAlc+CinAlc.SD*2,lty=2)
abline(v=CinAlc+CinAlc.SD*3,lty=2)
abline(v=CinAlc-CinAlc.SD,lty=2)
abline(v=CinAlc-CinAlc.SD*2,lty=2)
abline(v=CinAlc-CinAlc.SD*3,lty=2)
abline(v=Data[11,6],col="green",lwd=4)
abline(v=Data[11,7],col="blue",lwd=3)
abline(v=Data[11,8],col="red",lwd=3)

#CycNPhos
X = seq(-4,4,length=1000)*CycNPhos.SD + CycNPhos
Y = dnorm(X, CycNPhos, CycNPhos.SD)
plot(X, Y, xlab="Proportion Represented", ylab ="Probability",main="CycNPhos")
abline(v=CycNPhos,lty=2)
abline(v=CycNPhos+CycNPhos.SD,lty=2)
abline(v=CycNPhos+CycNPhos.SD*2,lty=2)
abline(v=CycNPhos+CycNPhos.SD*3,lty=2)
abline(v=CycNPhos-CycNPhos.SD,lty=2)
abline(v=CycNPhos-CycNPhos.SD*2,lty=2)
abline(v=CycNPhos-CycNPhos.SD*3,lty=2)
abline(v=Data[12,6],col="green",lwd=4)
abline(v=Data[12,7],col="blue",lwd=3)
abline(v=Data[12,8],col="red",lwd=3)

#CystPep
X = seq(-4,4,length=1000)*CystPep.SD + CystPep
Y = dnorm(X, CystPep, CystPep.SD)
plot(X, Y, xlab="Proportion Represented", ylab ="Probability",main="CystPep")
abline(v=CystPep,lty=2)
abline(v=CystPep+CystPep.SD,lty=2)
abline(v=CystPep+CystPep.SD*2,lty=2)
abline(v=CystPep+CystPep.SD*3,lty=2)
abline(v=CystPep-CystPep.SD,lty=2)
abline(v=CystPep-CystPep.SD*2,lty=2)
abline(v=CystPep-CystPep.SD*3,lty=2)
abline(v=Data[13,6],col="green",lwd=4)
abline(v=Data[13,7],col="blue",lwd=3)
abline(v=Data[13,8],col="red",lwd=3)

#EndoNuc ###NO HITS
#X = seq(-4,4,length=1000)*EndoNuc.SD + EndoNuc
#Y = dnorm(X, EndoNuc, EndoNuc.SD)
#plot(X, Y, xlab="Proportion Represented", ylab ="Probability",main="EndoNuc")
#abline(v=EndoNuc,lty=2)
#abline(v=EndoNuc+EndoNuc.SD,lty=2)
#abline(v=EndoNuc+EndoNuc.SD*2,lty=2)
#abline(v=EndoNuc+EndoNuc.SD*3,lty=2)
#abline(v=EndoNuc-EndoNuc.SD,lty=2)
#abline(v=EndoNuc-EndoNuc.SD*2,lty=2)
#abline(v=EndoNuc-EndoNuc.SD*3,lty=2)
#abline(v=Data[14,6],col="green",lwd=4)
#abline(v=Data[14,7],col="blue",lwd=3)
#abline(v=Data[14,8],col="red",lwd=3)

#FormateDH   ###NO HITS
#X = seq(-4,4,length=1000)*FormateDH.SD + FormateDH
#Y = dnorm(X, FormateDH, FormateDH.SD)
#plot(X, Y, xlab="Proportion Represented", ylab ="Probability",main="FormateDH")
#abline(v=FormateDH,lty=2)
#abline(v=FormateDH+FormateDH.SD,lty=2)
#abline(v=FormateDH+FormateDH.SD*2,lty=2)
#abline(v=FormateDH+FormateDH.SD*3,lty=2)
#abline(v=FormateDH-FormateDH.SD,lty=2)
#abline(v=FormateDH-FormateDH.SD*2,lty=2)
#abline(v=FormateDH-FormateDH.SD*3,lty=2)
#abline(v=Data[15,6],col="green",lwd=4)
#abline(v=Data[15,7],col="blue",lwd=3)
#abline(v=Data[15,8],col="red",lwd=3)

#FrucBPA 
X = seq(-4,4,length=1000)*FrucBPA.SD + FrucBPA
Y = dnorm(X, FrucBPA, FrucBPA.SD)
plot(X, Y, xlab="Proportion Represented", ylab ="Probability",main="FrucBPA")
abline(v=FrucBPA,lty=2)
abline(v=FrucBPA+FrucBPA.SD,lty=2)
abline(v=FrucBPA+FrucBPA.SD*2,lty=2)
abline(v=FrucBPA+FrucBPA.SD*3,lty=2)
abline(v=FrucBPA-FrucBPA.SD,lty=2)
abline(v=FrucBPA-FrucBPA.SD*2,lty=2)
abline(v=FrucBPA-FrucBPA.SD*3,lty=2)
abline(v=Data[16,6],col="green",lwd=4)
abline(v=Data[16,7],col="blue",lwd=3)
abline(v=Data[16,8],col="red",lwd=3)

#Glucosid ###NO HITS
#X = seq(-4,4,length=1000)*Glucosid.SD + Glucosid
#Y = dnorm(X, Glucosid, Glucosid.SD)
#plot(X, Y, xlab="Proportion Represented", ylab ="Probability",main="Glucosid")
#abline(v=Glucosid,lty=2)
#abline(v=Glucosid+Glucosid.SD,lty=2)
#abline(v=Glucosid+Glucosid.SD*2,lty=2)
#abline(v=Glucosid+Glucosid.SD*3,lty=2)
#abline(v=Glucosid-Glucosid.SD,lty=2)
#abline(v=Glucosid-Glucosid.SD*2,lty=2)
#abline(v=Glucosid-Glucosid.SD*3,lty=2)
#abline(v=Data[17,6],col="green",lwd=4)
#abline(v=Data[17,7],col="blue",lwd=2)
#abline(v=Data[17,8],col="red",lwd=3)

#GlutTrans
X = seq(-4,4,length=1000)*GlutTrans.SD + GlutTrans
Y = dnorm(X, GlutTrans, GlutTrans.SD)
plot(X, Y, xlab="Proportion Represented", ylab ="Probability",main="GlutTrans")
abline(v=GlutTrans,lty=2)
abline(v=GlutTrans+GlutTrans.SD,lty=2)
abline(v=GlutTrans+GlutTrans.SD*2,lty=2)
abline(v=GlutTrans+GlutTrans.SD*3,lty=2)
abline(v=GlutTrans-GlutTrans.SD,lty=2)
abline(v=GlutTrans-GlutTrans.SD*2,lty=2)
abline(v=GlutTrans-GlutTrans.SD*3,lty=2)
abline(v=Data[18,6],col="green",lwd=4)
abline(v=Data[18,7],col="blue",lwd=2)
abline(v=Data[18,8],col="red",lwd=3)

#Lipase
X = seq(-4,4,length=1000)*Lipase.SD + Lipase
Y = dnorm(X, Lipase, Lipase.SD)
plot(X, Y, xlab="Proportion Represented", ylab ="Probability",main="Lipase")
abline(v=Lipase,lty=2)
abline(v=Lipase+Lipase.SD,lty=2)
abline(v=Lipase+Lipase.SD*2,lty=2)
abline(v=Lipase+Lipase.SD*3,lty=2)
abline(v=Lipase-Lipase.SD,lty=2)
abline(v=Lipase-Lipase.SD*2,lty=2)
abline(v=Lipase-Lipase.SD*3,lty=2)
abline(v=Data[19,6],col="green",lwd=4)
abline(v=Data[19,7],col="blue",lwd=2)
abline(v=Data[19,8],col="red",lwd=3)

#LipTrans
X = seq(-4,4,length=1000)*LipTrans.SD + LipTrans
Y = dnorm(X, LipTrans, LipTrans.SD)
plot(X, Y, xlab="Proportion Represented", ylab ="Probability",main="LipTrans")
abline(v=LipTrans,lty=2)
abline(v=LipTrans+LipTrans.SD,lty=2)
abline(v=LipTrans+LipTrans.SD*2,lty=2)
abline(v=LipTrans+LipTrans.SD*3,lty=2)
abline(v=LipTrans-LipTrans.SD,lty=2)
abline(v=LipTrans-LipTrans.SD*2,lty=2)
abline(v=LipTrans-LipTrans.SD*3,lty=2)
abline(v=Data[20,6],col="green",lwd=4)
abline(v=Data[20,7],col="blue",lwd=2)
abline(v=Data[20,8],col="red",lwd=3)

#MethylNH ###NO HITS
#X = seq(-4,4,length=1000)*MethylNH.SD + MethylNH
#Y = dnorm(X, MethylNH, MethylNH.SD)
#plot(X, Y, xlab="Proportion Represented", ylab ="Probability",main="MethylNH")
#abline(v=MethylNH,lty=2)
#abline(v=MethylNH+MethylNH.SD,lty=2)
#abline(v=MethylNH+MethylNH.SD*2,lty=2)
#abline(v=MethylNH+MethylNH.SD*3,lty=2)
#abline(v=MethylNH-MethylNH.SD,lty=2)
#abline(v=MethylNH-MethylNH.SD*2,lty=2)
#abline(v=MethylNH-MethylNH.SD*3,lty=2)
#abline(v=Data[21,6],col="green",lwd=4)
#abline(v=Data[21,7],col="blue",lwd=2)
#abline(v=Data[21,8],col="red",lwd=3)

#Perox
X = seq(-4,4,length=1000)*Perox.SD + Perox
Y = dnorm(X, Perox, Perox.SD)
plot(X, Y, xlab="Proportion Represented", ylab ="Probability",main="Perox")
abline(v=Perox,lty=2)
abline(v=Perox+Perox.SD,lty=2)
abline(v=Perox+Perox.SD*2,lty=2)
abline(v=Perox+Perox.SD*3,lty=2)
abline(v=Perox-Perox.SD,lty=2)
abline(v=Perox-Perox.SD*2,lty=2)
abline(v=Perox-Perox.SD*3,lty=2)
abline(v=Data[22,6],col="green",lwd=4)
abline(v=Data[22,7],col="blue",lwd=2)
abline(v=Data[22,8],col="red",lwd=3)

#Phosp
X = seq(-4,4,length=1000)*Phosp.SD + Phosp
Y = dnorm(X, Phosp, Phosp.SD)
plot(X, Y, xlab="Percent Representation", ylab ="Probability",main="Phosphatase Activity")
abline(v=Phosp,lty=2)
abline(v=Phosp+Phosp.SD,lty=2)
abline(v=Phosp+Phosp.SD*2,lty=2)
abline(v=Phosp+Phosp.SD*3,lty=2)
abline(v=Phosp+Phosp.SD*4,lty=2)
abline(v=Phosp+Phosp.SD*5,lty=2)
abline(v=Phosp+Phosp.SD*6,lty=2)
abline(v=Phosp+Phosp.SD*7,lty=2)
abline(v=Phosp+Phosp.SD*8,lty=2)
abline(v=Phosp+Phosp.SD*9,lty=2)
abline(v=Phosp+Phosp.SD*10,lty=2)
abline(v=Phosp+Phosp.SD*11,lty=2)
abline(v=Phosp+Phosp.SD*12,lty=2)
abline(v=Phosp+Phosp.SD*13,lty=2)
abline(v=Phosp-Phosp.SD,lty=2)
abline(v=Phosp-Phosp.SD*2,lty=2)
abline(v=Phosp-Phosp.SD*3,lty=2)
abline(v=Data[23,6],col="green",lwd=4)
abline(v=Data[23,7],col="blue",lwd=2)
abline(v=Data[23,8],col="red",lwd=3)

#Phoslip
X = seq(-4,4,length=1000)*Phoslip.SD + Phoslip
Y = dnorm(X, Phoslip, Phoslip.SD)
plot(X, Y, xlab="Proportion Represented", ylab ="Probability",main="Phoslip")
abline(v=Phoslip,lty=2)
abline(v=Phoslip+Phoslip.SD,lty=2)
abline(v=Phoslip+Phoslip.SD*2,lty=2)
abline(v=Phoslip+Phoslip.SD*3,lty=2)
abline(v=Phoslip-Phoslip.SD,lty=2)
abline(v=Phoslip-Phoslip.SD*2,lty=2)
abline(v=Phoslip-Phoslip.SD*3,lty=2)
abline(v=Data[24,6],col="green",lwd=4)
abline(v=Data[24,7],col="blue",lwd=2)
abline(v=Data[24,8],col="red",lwd=3)

#Polygal
X = seq(-4,4,length=1000)*Polygal.SD + Polygal
Y = dnorm(X, Polygal, Polygal.SD)
plot(X, Y, xlab="Proportion Represented", ylab ="Probability",main="Polygal")
abline(v=Polygal,lty=2)
abline(v=Polygal+Polygal.SD,lty=2)
abline(v=Polygal+Polygal.SD*2,lty=2)
abline(v=Polygal+Polygal.SD*3,lty=2)
abline(v=Polygal-Polygal.SD,lty=2)
abline(v=Polygal-Polygal.SD*2,lty=2)
abline(v=Polygal-Polygal.SD*3,lty=2)
abline(v=Data[25,6],col="green",lwd=4)
abline(v=Data[25,7],col="blue",lwd=2)
abline(v=Data[25,8],col="red",lwd=3)

#PolygalInhib  ###NO HITS
X = seq(-4,4,length=1000)*PolygalInhib.SD + PolygalInhib
Y = dnorm(X, PolygalInhib, PolygalInhib.SD)
plot(X, Y, xlab="Proportion Represented", ylab ="Probability",main="PolygalInhib")
abline(v=PolygalInhib,lty=2)
abline(v=PolygalInhib+PolygalInhib.SD,lty=2)
abline(v=PolygalInhib+PolygalInhib.SD*2,lty=2)
abline(v=PolygalInhib+PolygalInhib.SD*3,lty=2)
abline(v=PolygalInhib-PolygalInhib.SD,lty=2)
abline(v=PolygalInhib-PolygalInhib.SD*2,lty=2)
abline(v=PolygalInhib-PolygalInhib.SD*3,lty=2)
abline(v=Data[26,6],col="green",lwd=4)
abline(v=Data[26,7],col="blue",lwd=2)
abline(v=Data[26,8],col="red",lwd=3)

#ProtHomo
X = seq(-4,4,length=1000)*ProtHomo.SD + ProtHomo
Y = dnorm(X, ProtHomo, ProtHomo.SD)
plot(X, Y, xlab="Proportion Represented", ylab ="Probability",main="ProtHomo")
abline(v=ProtHomo,lty=2)
abline(v=ProtHomo+ProtHomo.SD,lty=2)
abline(v=ProtHomo+ProtHomo.SD*2,lty=2)
abline(v=ProtHomo+ProtHomo.SD*3,lty=2)
abline(v=ProtHomo-ProtHomo.SD,lty=2)
abline(v=ProtHomo-ProtHomo.SD*2,lty=2)
abline(v=ProtHomo-ProtHomo.SD*3,lty=2)
abline(v=Data[27,6],col="green",lwd=4)
abline(v=Data[27,7],col="blue",lwd=2)
abline(v=Data[27,8],col="red",lwd=3)

#RiboNuc
X = seq(-4,4,length=1000)*RiboNuc.SD + RiboNuc
Y = dnorm(X, RiboNuc, RiboNuc.SD)
plot(X, Y, xlab="Proportion Represented", ylab ="Probability",main="RiboNuc")
abline(v=RiboNuc,lty=2)
abline(v=RiboNuc+RiboNuc.SD,lty=2)
abline(v=RiboNuc+RiboNuc.SD*2,lty=2)
abline(v=RiboNuc+RiboNuc.SD*3,lty=2)
abline(v=RiboNuc-RiboNuc.SD,lty=2)
abline(v=RiboNuc-RiboNuc.SD*2,lty=2)
abline(v=RiboNuc-RiboNuc.SD*3,lty=2)
abline(v=Data[28,6],col="green",lwd=4)
abline(v=Data[28,7],col="blue",lwd=2)
abline(v=Data[28,8],col="red",lwd=3)

#SerCarPep
X = seq(-4,4,length=1000)*SerCarPep.SD + SerCarPep
Y = dnorm(X, SerCarPep, SerCarPep.SD)
plot(X, Y, xlab="Proportion Represented", ylab ="Probability",main="SerCarPep")
abline(v=SerCarPep,lty=2)
abline(v=SerCarPep+SerCarPep.SD,lty=2)
abline(v=SerCarPep+SerCarPep.SD*2,lty=2)
abline(v=SerCarPep+SerCarPep.SD*3,lty=2)
abline(v=SerCarPep-SerCarPep.SD,lty=2)
abline(v=SerCarPep-SerCarPep.SD*2,lty=2)
abline(v=SerCarPep-SerCarPep.SD*3,lty=2)
abline(v=Data[29,6],col="green",lwd=4)
abline(v=Data[29,7],col="blue",lwd=2)
abline(v=Data[29,8],col="red",lwd=3)

#NaTrans ###NO HITS
#X = seq(-4,4,length=1000)*NaTrans.SD + NaTrans
#Y = dnorm(X, NaTrans, NaTrans.SD)
#plot(X, Y, xlab="Proportion Represented", ylab ="Probability",main="NaTrans")
#abline(v=NaTrans,lty=2)
#abline(v=NaTrans+NaTrans.SD,lty=2)
#abline(v=NaTrans+NaTrans.SD*2,lty=2)
#abline(v=NaTrans+NaTrans.SD*3,lty=2)
#abline(v=NaTrans-NaTrans.SD,lty=2)
#abline(v=NaTrans-NaTrans.SD*2,lty=2)
#abline(v=NaTrans-NaTrans.SD*3,lty=2)
#abline(v=Data[30,6],col="green",lwd=4)
#abline(v=Data[30,7],col="blue",lwd=2)
#abline(v=Data[30,8],col="red",lwd=3)

#SuperOx
X = seq(-4,4,length=1000)*SuperOx.SD + SuperOx
Y = dnorm(X, SuperOx, SuperOx.SD)
plot(X, Y, xlab="Proportion Represented", ylab ="Probability",main="SuperOx")
abline(v=SuperOx,lty=2)
abline(v=SuperOx+SuperOx.SD,lty=2)
abline(v=SuperOx+SuperOx.SD*2,lty=2)
abline(v=SuperOx+SuperOx.SD*3,lty=2)
abline(v=SuperOx-SuperOx.SD,lty=2)
abline(v=SuperOx-SuperOx.SD*2,lty=2)
abline(v=SuperOx-SuperOx.SD*3,lty=2)
abline(v=Data[31,6],col="green",lwd=4)
abline(v=Data[31,7],col="blue",lwd=2)
abline(v=Data[31,8],col="red",lwd=3)

#Symplast   ###NO HITS
#X = seq(-4,4,length=1000)*Symplast.SD + Symplast
#Y = dnorm(X, Symplast, Symplast.SD)
#plot(X, Y, xlab="Proportion Represented", ylab ="Probability",main="Symplast")
#abline(v=Symplast,lty=2)
#abline(v=Symplast+Symplast.SD,lty=2)
#abline(v=Symplast+Symplast.SD*2,lty=2)
#abline(v=Symplast+Symplast.SD*3,lty=2)
#abline(v=Symplast-Symplast.SD,lty=2)
#abline(v=Symplast-Symplast.SD*2,lty=2)
#abline(v=Symplast-Symplast.SD*3,lty=2)
#abline(v=Data[32,6],col="green",lwd=4)
#abline(v=Data[32,7],col="blue",lwd=2)
#abline(v=Data[32,8],col="red",lwd=3)

#ThioGluc
X = seq(-4,4,length=1000)*ThioGluc.SD + ThioGluc
Y = dnorm(X, ThioGluc, ThioGluc.SD)
plot(X, Y, xlab="Proportion Represented", ylab ="Probability",main="ThioGluc")
abline(v=ThioGluc,lty=2)
abline(v=ThioGluc+ThioGluc.SD,lty=2)
abline(v=ThioGluc+ThioGluc.SD*2,lty=2)
abline(v=ThioGluc+ThioGluc.SD*3,lty=2)
abline(v=ThioGluc-ThioGluc.SD,lty=2)
abline(v=ThioGluc-ThioGluc.SD*2,lty=2)
abline(v=ThioGluc-ThioGluc.SD*3,lty=2)
abline(v=Data[33,6],col="green",lwd=4)
abline(v=Data[33,7],col="blue",lwd=2)
abline(v=Data[33,8],col="red",lwd=3)

#H20Chan
X = seq(-4,4,length=1000)*H20Chan.SD + H20Chan
Y = dnorm(X, H20Chan, H20Chan.SD)
plot(X, Y, xlab="Proportion Represented", ylab ="Probability",main="H20Chan")
abline(v=H20Chan,lty=2)
abline(v=H20Chan+H20Chan.SD,lty=2)
abline(v=H20Chan+H20Chan.SD*2,lty=2)
abline(v=H20Chan+H20Chan.SD*3,lty=2)
abline(v=H20Chan-H20Chan.SD,lty=2)
abline(v=H20Chan-H20Chan.SD*2,lty=2)
abline(v=H20Chan-H20Chan.SD*3,lty=2)
abline(v=Data[34,6],col="green",lwd=4)
abline(v=Data[34,7],col="blue",lwd=2)
abline(v=Data[34,8],col="red",lwd=3)

#Xyl ###NO HITS
#X = seq(-4,4,length=1000)*Xyl.SD + Xyl
#Y = dnorm(X, Xyl, Xyl.SD)
#plot(X, Y, xlab="Proportion Represented", ylab ="Probability",main="Xyl")
#abline(v=Xyl,lty=2)
#abline(v=Xyl+Xyl.SD,lty=2)
#abline(v=Xyl+Xyl.SD*2,lty=2)
#abline(v=Xyl+Xyl.SD*3,lty=2)
#abline(v=Xyl-Xyl.SD,lty=2)
#abline(v=Xyl-Xyl.SD*2,lty=2)
#abline(v=Xyl-Xyl.SD*3,lty=2)
#abline(v=Data[35,6],col="green",lwd=4)
#abline(v=Data[35,7],col="blue",lwd=2)
#abline(v=Data[35,8],col="red",lwd=3)

#HeatShock
X = seq(-4,4,length=1000)*HeatShock.SD + HeatShock
Y = dnorm(X, HeatShock, HeatShock.SD)
plot(X, Y, xlab="Proportion Represented", ylab ="Probability",main="HeatShock")
abline(v=HeatShock,lty=2)
abline(v=HeatShock+HeatShock.SD,lty=2)
abline(v=HeatShock+HeatShock.SD*2,lty=2)
abline(v=HeatShock+HeatShock.SD*3,lty=2)
abline(v=HeatShock-HeatShock.SD,lty=2)
abline(v=HeatShock-HeatShock.SD*2,lty=2)
abline(v=HeatShock-HeatShock.SD*3,lty=2)
abline(v=Data[36,6],col="green",lwd=4)
abline(v=Data[36,7],col="blue",lwd=3)
abline(v=Data[36,8],col="red",lwd=3)

Summary<-matrix(nrow=29,ncol=10)
Summary[1,]<-c("CarnivTot:","Sarracenia alata",(Data[38,6]-CarnivTot)/CarnivTot.SD,"","Genlisea aurea",(Data[38,7]-CarnivTot)/CarnivTot.SD,"","Drosera capensis",(Data[38,8]-CarnivTot)/CarnivTot.SD,"")
Summary[2,] <- c("Actin:","Sarracenia alata",(Data[1,6]-Actin)/Actin.SD,"","Genlisea aurea",(Data[1,7]-Actin)/Actin.SD,"","Drosera capensis",(Data[1,8]-Actin)/Actin.SD,"")
Summary[3,] <- c("AGal","Sarracenia alata",(Data[2,6]-AGal)/AGal.SD,"","Genlisea aurea",(Data[2,7]-AGal)/AGal.SD,"","Drosera capensis",(Data[2,8]-AGal)/AGal.SD,"")
Summary[4,] <- c("AltOx:","Sarracenia alata",(Data[3,6]-AltOx)/AltOx.SD,"","Genlisea aurea",(Data[3,7]-AltOx)/AltOx.SD,"","Drosera capensis",(Data[3,8]-AltOx)/AltOx.SD,"")
Summary[5,] <- c("NHTrans:","Sarracenia alata",(Data[4,6]-NHTrans)/NHTrans.SD,"","Genlisea aurea",(Data[4,7]-NHTrans)/NHTrans.SD,"","Drosera capensis",(Data[4,8]-NHTrans)/NHTrans.SD,"")
Summary[6,] <- c("AspPep:","Sarracenia alata",(Data[5,6]-AspPep)/AspPep.SD,"","Genlisea aurea",(Data[5,7]-AspPep)/AspPep.SD,"","Drosera capensis",(Data[5,8]-AspPep)/AspPep.SD,"")
Summary[7,] <- c("ATP_ADP:","Sarracenia alata",(Data[6,6]-ATP_ADP)/ATP_ADP.SD,"","Genlisea aurea",(Data[6,7]-ATP_ADP)/ATP_ADP.SD,"","Drosera capensis",(Data[6,8]-ATP_ADP)/ATP_ADP.SD,"")
Summary[8,] <- c("ATP:","Sarracenia alata",(Data[7,6]-ATP)/ATP.SD,"","Genlisea aurea",(Data[7,7]-ATP)/ATP.SD,"","Drosera capensis",(Data[7,8]-ATP)/ATP.SD,"")
Summary[9,] <- c("BGal:","Sarracenia alata",(Data[8,6]-BGal)/BGal.SD,"","Genlisea aurea",(Data[8,7]-BGal)/BGal.SD,"","Drosera capensis",(Data[8,8]-BGal)/BGal.SD,"")
Summary[10,] <- c("Chit:","Sarracenia alata",(Data[10,6]-Chit)/Chit.SD,"","Genlisea aurea",(Data[10,7]-Chit)/Chit.SD,"","Drosera capensis",(Data[10,8]-Chit)/Chit.SD,"")
Summary[11,] <- c("CinAlc:","Sarracenia alata",(Data[11,6]-CinAlc)/CinAlc.SD,"","Genlisea aurea",(Data[11,7]-CinAlc)/CinAlc.SD,"","Drosera capensis",(Data[11,8]-CinAlc)/CinAlc.SD,"")
Summary[12,] <- c("CycNPhos:","Sarracenia alata",(Data[12,6]-CycNPhos)/CycNPhos.SD,"","Genlisea aurea",(Data[12,7]-CycNPhos)/CycNPhos.SD,"","Drosera capensis",(Data[12,8]-CycNPhos)/CycNPhos.SD,"")
Summary[13,] <- c("CystPep:","Sarracenia alata",(Data[13,6]-CystPep)/CystPep.SD,"","Genlisea aurea",(Data[13,7]-CystPep)/CystPep.SD,"","Drosera capensis",(Data[13,8]-CystPep)/CystPep.SD,"")
Summary[14,] <- c("FrucBPA:","Sarracenia alata",(Data[16,6]-FrucBPA)/FrucBPA.SD,"","Genlisea aurea",(Data[16,7]-FrucBPA)/FrucBPA.SD,"","Drosera capensis",(Data[16,8]-FrucBPA)/FrucBPA.SD,"")
Summary[15,] <- c("GlutTrans:","Sarracenia alata",(Data[18,6]-GlutTrans)/GlutTrans.SD,"","Genlisea aurea",(Data[18,7]-GlutTrans)/GlutTrans.SD,"","Drosera capensis",(Data[18,8]-GlutTrans)/GlutTrans.SD,"")
Summary[16,] <- c("Lipase:","Sarracenia alata",(Data[19,6]-Lipase)/Lipase.SD,"","Genlisea aurea",(Data[19,7]-Lipase)/Lipase.SD,"","Drosera capensis",(Data[19,8]-Lipase)/Lipase.SD,"")
Summary[17,] <- c("LipTrans:","Sarracenia alata",(Data[20,6]-LipTrans)/LipTrans.SD,"","Genlisea aurea",(Data[20,7]-LipTrans)/LipTrans.SD,"","Drosera capensis",(Data[20,8]-LipTrans)/LipTrans.SD,"")
Summary[18,] <- c("Perox:","Sarracenia alata",(Data[22,6]-Perox)/Perox.SD,"","Genlisea aurea",(Data[22,7]-Perox)/Perox.SD,"","Drosera capensis",(Data[22,8]-Perox)/Perox.SD,"")
Summary[19,] <- c("Phosp:","Sarracenia alata",(Data[23,6]-Phosp)/Phosp.SD,"","Genlisea aurea",(Data[23,7]-Phosp)/Phosp.SD,"","Drosera capensis",(Data[23,8]-Phosp)/Phosp.SD,"")
Summary[20,] <- c("Phoslip:","Sarracenia alata",(Data[24,6]-Phoslip)/Phoslip.SD,"","Genlisea aurea",(Data[24,7]-Phoslip)/Phoslip.SD,"","Drosera capensis",(Data[24,8]-Phoslip)/Phoslip.SD,"")
Summary[21,] <- c("Polygal:","Sarracenia alata",(Data[25,6]-Polygal)/Polygal.SD,"","Genlisea aurea",(Data[25,7]-Polygal)/Polygal.SD,"","Drosera capensis",(Data[25,8]-Polygal)/Polygal.SD,"")
Summary[22,] <- c("ProtHomo:","Sarracenia alata",(Data[27,6]-ProtHomo)/ProtHomo.SD,"","Genlisea aurea",(Data[27,7]-ProtHomo)/ProtHomo.SD,"","Drosera capensis",(Data[27,8]-ProtHomo)/ProtHomo.SD,"")
Summary[23,] <- c("RiboNuc:","Sarracenia alata",(Data[28,6]-RiboNuc)/RiboNuc.SD,"","Genlisea aurea",(Data[28,7]-RiboNuc)/RiboNuc.SD,"","Drosera capensis",(Data[28,8]-RiboNuc)/RiboNuc.SD,"")
Summary[24,] <- c("SerCarPep:","Sarracenia alata",(Data[29,6]-SerCarPep)/SerCarPep.SD,"","Genlisea aurea",(Data[29,7]-SerCarPep)/SerCarPep.SD,"","Drosera capensis",(Data[29,8]-SerCarPep)/SerCarPep.SD,"")
Summary[25,] <- c("SuperOx:","Sarracenia alata",(Data[31,6]-SuperOx)/SuperOx.SD,"","Genlisea aurea",(Data[31,7]-SuperOx)/SuperOx.SD,"","Drosera capensis",(Data[31,8]-SuperOx)/SuperOx.SD,"")
Summary[26,] <- c("ThioGluc:","Sarracenia alata",(Data[33,6]-ThioGluc)/ThioGluc.SD,"","Genlisea aurea",(Data[33,7]-ThioGluc)/ThioGluc.SD,"","Drosera capensis",(Data[33,8]-ThioGluc)/ThioGluc.SD,"")
Summary[27,] <- c("H20Chan:","Sarracenia alata",(Data[34,6]-H20Chan)/H20Chan.SD,"","Genlisea aurea",(Data[34,7]-H20Chan)/H20Chan.SD,"","Drosera capensis",(Data[34,8]-H20Chan)/H20Chan.SD,"")
Summary[28,] <- c("HeatShock:","Sarracenia alata",(Data[36,6]-HeatShock)/HeatShock.SD,"","Genlisea aurea",(Data[36,7]-HeatShock)/HeatShock.SD,"","Drosera capensis",(Data[36,8]-HeatShock)/HeatShock.SD,"")
Summary[29,] <- c("PolygalInhib:","Sarracenia alata",(Data[26,6]-PolygalInhib)/PolygalInhib.SD,"","Genlisea aurea",(Data[26,7]-PolygalInhib)/PolygalInhib.SD,"","Drosera capensis",(Data[26,8]-PolygalInhib)/PolygalInhib.SD,"")


Summary[1,4] <- pnorm((as.numeric(Summary[1,3])),lower.tail=FALSE)
Summary[2,4] <- pnorm((as.numeric(Summary[2,3])), lower.tail=FALSE)
Summary[3,4] <- pnorm((as.numeric(Summary[3,3])), lower.tail=FALSE)
Summary[4,4] <- pnorm((as.numeric(Summary[4,3])), lower.tail=FALSE)
Summary[5,4] <- pnorm((as.numeric(Summary[5,3])), lower.tail=FALSE)
Summary[6,4] <- pnorm((as.numeric(Summary[6,3])), lower.tail=FALSE)
Summary[7,4] <- pnorm((as.numeric(Summary[7,3])), lower.tail=FALSE)
Summary[8,4] <- pnorm((as.numeric(Summary[8,3])), lower.tail=FALSE)
Summary[9,4] <- pnorm((as.numeric(Summary[9,3])), lower.tail=FALSE)
Summary[10,4] <- pnorm((as.numeric(Summary[10,3])), lower.tail=FALSE)
Summary[11,4] <- pnorm((as.numeric(Summary[11,3])), lower.tail=FALSE)
Summary[12,4] <- pnorm((as.numeric(Summary[12,3])), lower.tail=FALSE)
Summary[13,4] <- pnorm((as.numeric(Summary[13,3])), lower.tail=FALSE)
Summary[14,4] <- pnorm((as.numeric(Summary[14,3])), lower.tail=FALSE)
Summary[15,4] <- pnorm((as.numeric(Summary[15,3])), lower.tail=FALSE)
Summary[16,4] <- pnorm((as.numeric(Summary[16,3])), lower.tail=FALSE)
Summary[17,4] <- pnorm((as.numeric(Summary[17,3])), lower.tail=FALSE)
Summary[18,4] <- pnorm((as.numeric(Summary[18,3])), lower.tail=FALSE)
Summary[19,4] <- pnorm((as.numeric(Summary[19,3])), lower.tail=FALSE)
Summary[20,4] <- pnorm((as.numeric(Summary[20,3])), lower.tail=FALSE)
Summary[21,4] <- pnorm((as.numeric(Summary[21,3])), lower.tail=FALSE)
Summary[22,4] <- pnorm((as.numeric(Summary[22,3])), lower.tail=FALSE)
Summary[23,4] <- pnorm((as.numeric(Summary[23,3])), lower.tail=FALSE)
Summary[24,4] <- pnorm((as.numeric(Summary[24,3])), lower.tail=FALSE)
Summary[25,4] <- pnorm((as.numeric(Summary[25,3])), lower.tail=FALSE)
Summary[26,4] <- pnorm((as.numeric(Summary[26,3])), lower.tail=FALSE)
Summary[27,4] <- pnorm((as.numeric(Summary[27,3])), lower.tail=FALSE)
Summary[28,4] <- pnorm((as.numeric(Summary[28,3])), lower.tail=FALSE)
Summary[29,4] <- pnorm((as.numeric(Summary[29,3])), lower.tail=FALSE)

Summary[1,7] <- pnorm((as.numeric(Summary[1,6])), lower.tail=FALSE)
Summary[2,7] <- pnorm((as.numeric(Summary[2,6])), lower.tail=FALSE)
Summary[3,7] <- pnorm((as.numeric(Summary[3,6])), lower.tail=FALSE)
Summary[4,7] <- pnorm((as.numeric(Summary[4,6])), lower.tail=FALSE)
Summary[5,7] <- pnorm((as.numeric(Summary[5,6])), lower.tail=FALSE)
Summary[6,7] <- pnorm((as.numeric(Summary[6,6])), lower.tail=FALSE)
Summary[7,7] <- pnorm((as.numeric(Summary[7,6])), lower.tail=FALSE)
Summary[8,7] <- pnorm((as.numeric(Summary[8,6])), lower.tail=FALSE)
Summary[9,7] <- pnorm((as.numeric(Summary[9,6])), lower.tail=FALSE)
Summary[10,7] <- pnorm((as.numeric(Summary[10,6])), lower.tail=FALSE)
Summary[11,7] <- pnorm((as.numeric(Summary[11,6])), lower.tail=FALSE)
Summary[12,7] <- pnorm((as.numeric(Summary[12,6])), lower.tail=FALSE)
Summary[13,7] <- pnorm((as.numeric(Summary[13,6])), lower.tail=FALSE)
Summary[14,7] <- pnorm((as.numeric(Summary[14,6])), lower.tail=FALSE)
Summary[15,7] <- pnorm((as.numeric(Summary[15,6])), lower.tail=FALSE)
Summary[16,7] <- pnorm((as.numeric(Summary[16,6])), lower.tail=FALSE)
Summary[17,7] <- pnorm((as.numeric(Summary[17,6])), lower.tail=FALSE)
Summary[18,7] <- pnorm((as.numeric(Summary[18,6])), lower.tail=FALSE)
Summary[19,7] <- pnorm((as.numeric(Summary[19,6])), lower.tail=FALSE)
Summary[20,7] <- pnorm((as.numeric(Summary[20,6])), lower.tail=FALSE)
Summary[21,7] <- pnorm((as.numeric(Summary[21,6])), lower.tail=FALSE)
Summary[22,7] <- pnorm((as.numeric(Summary[22,6])), lower.tail=FALSE)
Summary[23,7] <- pnorm((as.numeric(Summary[23,6])), lower.tail=FALSE)
Summary[24,7] <- pnorm((as.numeric(Summary[24,6])), lower.tail=FALSE)
Summary[25,7] <- pnorm((as.numeric(Summary[25,6])), lower.tail=FALSE)
Summary[26,7] <- pnorm((as.numeric(Summary[26,6])), lower.tail=FALSE)
Summary[27,7] <- pnorm((as.numeric(Summary[27,6])), lower.tail=FALSE)
Summary[28,7] <- pnorm((as.numeric(Summary[28,6])), lower.tail=FALSE)
Summary[29,7] <- pnorm((as.numeric(Summary[29,6])), lower.tail=FALSE)

Summary[1,10] <- pnorm((as.numeric(Summary[1,9])), lower.tail=FALSE)
Summary[2,10] <- pnorm((as.numeric(Summary[2,9])), lower.tail=FALSE)
Summary[3,10] <- pnorm((as.numeric(Summary[3,9])), lower.tail=FALSE)
Summary[4,10] <- pnorm((as.numeric(Summary[4,9])), lower.tail=FALSE)
Summary[5,10] <- pnorm((as.numeric(Summary[5,9])), lower.tail=FALSE)
Summary[6,10] <- pnorm((as.numeric(Summary[6,9])), lower.tail=FALSE)
Summary[7,10] <- pnorm((as.numeric(Summary[7,9])), lower.tail=FALSE)
Summary[8,10] <- pnorm((as.numeric(Summary[8,9])), lower.tail=FALSE)
Summary[9,10] <- pnorm((as.numeric(Summary[9,9])), lower.tail=FALSE)
Summary[10,10] <- pnorm((as.numeric(Summary[10,9])), lower.tail=FALSE)
Summary[11,10] <- pnorm((as.numeric(Summary[11,9])), lower.tail=FALSE)
Summary[12,10] <- pnorm((as.numeric(Summary[12,9])), lower.tail=FALSE)
Summary[13,10] <- pnorm((as.numeric(Summary[13,9])), lower.tail=FALSE)
Summary[14,10] <- pnorm((as.numeric(Summary[14,9])), lower.tail=FALSE)
Summary[15,10] <- pnorm((as.numeric(Summary[15,9])), lower.tail=FALSE)
Summary[16,10] <- pnorm((as.numeric(Summary[16,9])), lower.tail=FALSE)
Summary[17,10] <- pnorm((as.numeric(Summary[17,9])), lower.tail=FALSE)
Summary[18,10] <- pnorm((as.numeric(Summary[18,9])), lower.tail=FALSE)
Summary[19,10] <- pnorm((as.numeric(Summary[19,9])), lower.tail=FALSE)
Summary[20,10] <- pnorm((as.numeric(Summary[20,9])), lower.tail=FALSE)
Summary[21,10] <- pnorm((as.numeric(Summary[21,9])), lower.tail=FALSE)
Summary[22,10] <- pnorm((as.numeric(Summary[22,9])), lower.tail=FALSE)
Summary[23,10] <- pnorm((as.numeric(Summary[23,9])), lower.tail=FALSE)
Summary[24,10] <- pnorm((as.numeric(Summary[24,9])), lower.tail=FALSE)
Summary[25,10] <- pnorm((as.numeric(Summary[25,9])), lower.tail=FALSE)
Summary[26,10] <- pnorm((as.numeric(Summary[26,9])), lower.tail=FALSE)
Summary[27,10] <- pnorm((as.numeric(Summary[27,9])), lower.tail=FALSE)
Summary[28,10] <- pnorm((as.numeric(Summary[28,9])), lower.tail=FALSE)
Summary[29,10] <- pnorm((as.numeric(Summary[29,9])), lower.tail=FALSE)

View(Summary)
